### ISSUE TITLE
problems with saving "thellier_gui.preferences" in PmagPy directory

### ISSUE THREAD

**Issue by A-Beguin** [PmagPy/PmagPy-Standalone-OSX#5] opened 2017-11-27 14:37 UTC
Hi all,

I have a problem with saving the "thellier_gui_preferences.py" file in which the specimen paleointensity preferences are saved. This file needs to be saved in the main PmagPy folder, then the program needs to be restart before seeing the change. 
Since I work with the stand alone version of the pmag_gui, I am not sure what my main PmagPy folder is. I have tried saving the "thellier_gui_preferences.py" file in the folder that is opened automatically (somewhere deep in my Mac, which is called pmagpy), I have tried saving the file in my working directory and I have tried saving the file at the same location as the pmag_gui.app (Desktop). Non of these locations seems to be the correct one. When I restart the program the default Thellier GUI statistics are shown and not the statistics I saved in the file. 

The message that pops-up after changing the preferences and clicking 'OK', tells me to save the " thellier_gui.preferences " file, the default name when clicking 'OK' is "thellier_gui_preferences.py". Which one should it be? (I have tried both files in all three locations, no luck)

Hopefully you can help me out so that I can run the auto-interpreter on my samples. 
Cheers,
Annemarieke Beguin
(Fort Hoofdijk, Utrecht University)

**Comment by moonshoes87** [comment] 2017-11-27 18:46
Hi Annemarieke.

Which version of the standalone are you using (e.g., 3.11.1)?  

I believe this has been fixed in the latest two versions of the standalone.  The location for the preferences is now determined in the program itself, so you shouldn't run into this problem.  Try re-downloading, and let me know if you still have troubles!

**Comment by A-Beguin** [comment] 2017-11-28 09:36
Hi Lori,

Thank you for helping me! I thought I had one of the latest versions, apparently not (I had 3.10.1), updating to the newest version helped. The preferences and criteria file are now easily saved and used when reloading the program. 

With the newest version (3.12.0) I now run in some other troubles. 
- The lab field is not displayed for the first sample, if I click on 'next' and then 'previous' it appears
- After selecting temperature bounds the B_anc stays empty, the green line is drawn and the specimen statistics are there (all green), also the Dec and Inc are given. If I click on 'save', the 'mean' intensity of all samples/site results is given, the B_anc stays empty. 
- When running the auto-interpreter, a KeyError appears in the terminal: KeyError: ‘specimen_frac’. In the file 'thellier_interpreter_all.txt' all the possible interpretations for all the samples are displayed, do I need to worry about this KeyError? 

Thanks,
Annemarieke

**Comment by moonshoes87** [comment] 2017-11-28 18:29
Hi Annemarieke,

I’m glad I could help!  As for your other problems, I’m not able to reproduce them with the data files I have.  Could you please send me your data files so I can investigate further?  

You can attach files here on Github, or if you prefer to keep them private, you can email them to me at ljonestrask@ucsd.edu.  

Thanks!
Lori

**Comment by moonshoes87** [comment] 2017-12-01 17:54
The secondary issues were caused because Thellier GUI expected the SCAT statistic to be used, and would break if it was not included.  That is fixed as of 3.13.0.

**Closed by moonshoes87** 2017-12-01 17:54 UTC
